### ISSUE TITLE
Hash URL issue

### ISSUE THREAD

**Issue by mohitkumat** [private-face/jquery.fullscreen#30]
Redirects to base URL e.g. **localhost:3000/#** from **localhost:3000/#/dashboard** or any other URL when switched to and fro full screen view.
I am using React with Flux on Chrome - Ubuntu.

**Comment by mohitkumat** [comment]
@private-face Any updates here?

**Comment by private-face** [comment]
@mohitkumat sorry, cannot reproduce your issue. Could you provide a code example?

**Comment by mohitkumat** [comment]
Sorry, my mistake, no issue with the plugin. It was just hash URLs vs '#' in anchor tag stuff.
Just a little preventDefault() did the job for me.
Thanks for the reply though.
