### ISSUE TITLE
requestFullscreen() is deprecated on insecure origins

### ISSUE THREAD

**Issue by friend8** [private-face/jquery.fullscreen#33]
The method `requestFullscreen()` is deprecated as of Chrome 44 the following warning appears using the fullscreen feature on a non-HTTPS page.

> `requestFullscreen()` is deprecated on insecure origins, and support will be removed in the future. You should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.

**Comment by platedodev** [comment]
You need SSL.

**Comment by private-face** [comment]
@friend8 Looks like Fullscreen was excluded from this proposal (check the document you referred to). API available and works on insecure origins in Chrome 55 without any warning.

But @platedodev is right, you do need SSL. You can grab a free certificate for your site at [Let's Encrypt](https://letsencrypt.org).
