### ISSUE TITLE
Prefixed fullscreen API is deprecated on Firefox

### ISSUE THREAD

**Issue by DavidAnderson684** [private-face/jquery.fullscreen#35]
On current versions of Firefox (I am using 47.0), the developer console shows a message:

Prefixed Fullscreen API is deprecated. Please use unprefixed API for fullscreen. For more help https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API

**Comment by private-face** [comment]
@DavidAnderson684 This is strange, plugin uses prefixed API only if unprefixed is not available. Is this issue still applicable? I am checking in Firefox 50 and don't see any messages.

**Comment by DavidAnderson684** [comment]
I can confirm that we no longer get this in the Firefox developer console (Firefox 51).
